# Generated by Django 3.1.7 on 2021-05-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='images',
            field=models.ManyToManyField(to='users.Image'),
        ),
    ]
