# Generated by Django 3.1.7 on 2021-03-28 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20210324_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='classroom',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='school.classroom'),
            preserve_default=False,
        ),
    ]
