# Generated by Django 3.1.7 on 2021-05-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_classroom_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='cabinet',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
